/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package org.netbeans.aspectj.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int ABSTRACT = 8;
  /** RegularExpression Id. */
  int ASSERT = 9;
  /** RegularExpression Id. */
  int BOOLEAN = 10;
  /** RegularExpression Id. */
  int BREAK = 11;
  /** RegularExpression Id. */
  int BYTE = 12;
  /** RegularExpression Id. */
  int CASE = 13;
  /** RegularExpression Id. */
  int CATCH = 14;
  /** RegularExpression Id. */
  int CHAR = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int CONST = 17;
  /** RegularExpression Id. */
  int CONTINUE = 18;
  /** RegularExpression Id. */
  int _DEFAULT = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int DOUBLE = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int ENUM = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int FINAL = 26;
  /** RegularExpression Id. */
  int FINALLY = 27;
  /** RegularExpression Id. */
  int FLOAT = 28;
  /** RegularExpression Id. */
  int FOR = 29;
  /** RegularExpression Id. */
  int GOTO = 30;
  /** RegularExpression Id. */
  int IF = 31;
  /** RegularExpression Id. */
  int IMPLEMENTS = 32;
  /** RegularExpression Id. */
  int IMPORT = 33;
  /** RegularExpression Id. */
  int INSTANCEOF = 34;
  /** RegularExpression Id. */
  int INT = 35;
  /** RegularExpression Id. */
  int INTERFACE = 36;
  /** RegularExpression Id. */
  int LONG = 37;
  /** RegularExpression Id. */
  int NATIVE = 38;
  /** RegularExpression Id. */
  int NEW = 39;
  /** RegularExpression Id. */
  int NULL = 40;
  /** RegularExpression Id. */
  int PACKAGE = 41;
  /** RegularExpression Id. */
  int PRIVATE = 42;
  /** RegularExpression Id. */
  int PROTECTED = 43;
  /** RegularExpression Id. */
  int PUBLIC = 44;
  /** RegularExpression Id. */
  int RETURN = 45;
  /** RegularExpression Id. */
  int SHORT = 46;
  /** RegularExpression Id. */
  int STATIC = 47;
  /** RegularExpression Id. */
  int STRICTFP = 48;
  /** RegularExpression Id. */
  int SUPER = 49;
  /** RegularExpression Id. */
  int SWITCH = 50;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 51;
  /** RegularExpression Id. */
  int THIS = 52;
  /** RegularExpression Id. */
  int THROW = 53;
  /** RegularExpression Id. */
  int THROWS = 54;
  /** RegularExpression Id. */
  int TRANSIENT = 55;
  /** RegularExpression Id. */
  int TRUE = 56;
  /** RegularExpression Id. */
  int TRY = 57;
  /** RegularExpression Id. */
  int VOID = 58;
  /** RegularExpression Id. */
  int VOLATILE = 59;
  /** RegularExpression Id. */
  int WHILE = 60;
  /** RegularExpression Id. */
  int ASPECT = 61;
  /** RegularExpression Id. */
  int AFTER = 62;
  /** RegularExpression Id. */
  int AROUND = 63;
  /** RegularExpression Id. */
  int BEFORE = 64;
  /** RegularExpression Id. */
  int POINTCUT = 65;
  /** RegularExpression Id. */
  int EXECUTION = 66;
  /** RegularExpression Id. */
  int RETURNING = 67;
  /** RegularExpression Id. */
  int PRIVILEGED = 68;
  /** RegularExpression Id. */
  int CALL = 69;
  /** RegularExpression Id. */
  int PERTARGET = 70;
  /** RegularExpression Id. */
  int PERTHIS = 71;
  /** RegularExpression Id. */
  int PERCFLOW = 72;
  /** RegularExpression Id. */
  int PERCFLOWBELOW = 73;
  /** RegularExpression Id. */
  int PERTYPEWITHIN = 74;
  /** RegularExpression Id. */
  int ISSINGLETON = 75;
  /** RegularExpression Id. */
  int THROWING = 76;
  /** RegularExpression Id. */
  int PROCEED = 77;
  /** RegularExpression Id. */
  int THISJOINPOINT = 78;
  /** RegularExpression Id. */
  int THISJOINPOINTSTATICPART = 79;
  /** RegularExpression Id. */
  int THISENCLOSINGJOINPOINTSTATICPART = 80;
  /** RegularExpression Id. */
  int DECLARE = 81;
  /** RegularExpression Id. */
  int PARENTS = 82;
  /** RegularExpression Id. */
  int WARNING = 83;
  /** RegularExpression Id. */
  int ERROR = 84;
  /** RegularExpression Id. */
  int SOFT = 85;
  /** RegularExpression Id. */
  int PRECEDENCE = 86;
  /** RegularExpression Id. */
  int _TYPE = 87;
  /** RegularExpression Id. */
  int _METHOD = 88;
  /** RegularExpression Id. */
  int _CONSTRUCTOR = 89;
  /** RegularExpression Id. */
  int _FIELD = 90;
  /** RegularExpression Id. */
  int INITIALIZATION = 91;
  /** RegularExpression Id. */
  int PREINITIALIZATION = 92;
  /** RegularExpression Id. */
  int STATICINITIALIZATION = 93;
  /** RegularExpression Id. */
  int GET = 94;
  /** RegularExpression Id. */
  int SET = 95;
  /** RegularExpression Id. */
  int HANDLER = 96;
  /** RegularExpression Id. */
  int ADVICEEXECUTION = 97;
  /** RegularExpression Id. */
  int WITHIN = 98;
  /** RegularExpression Id. */
  int WITHINCODE = 99;
  /** RegularExpression Id. */
  int CFLOW = 100;
  /** RegularExpression Id. */
  int CFLOWBELOW = 101;
  /** RegularExpression Id. */
  int TARGET = 102;
  /** RegularExpression Id. */
  int ARGS = 103;
  /** RegularExpression Id. */
  int _THIS = 104;
  /** RegularExpression Id. */
  int _TARGET = 105;
  /** RegularExpression Id. */
  int _ARGS = 106;
  /** RegularExpression Id. */
  int _WITHIN = 107;
  /** RegularExpression Id. */
  int _ANNOTATION = 108;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 109;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 110;
  /** RegularExpression Id. */
  int HEX_LITERAL = 111;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 112;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 113;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 114;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 115;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 116;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 117;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 118;
  /** RegularExpression Id. */
  int STRING_LITERAL = 119;
  /** RegularExpression Id. */
  int IDENTIFIER = 120;
  /** RegularExpression Id. */
  int LETTER = 121;
  /** RegularExpression Id. */
  int PART_LETTER = 122;
  /** RegularExpression Id. */
  int LPAREN = 123;
  /** RegularExpression Id. */
  int RPAREN = 124;
  /** RegularExpression Id. */
  int LBRACE = 125;
  /** RegularExpression Id. */
  int RBRACE = 126;
  /** RegularExpression Id. */
  int LBRACKET = 127;
  /** RegularExpression Id. */
  int RBRACKET = 128;
  /** RegularExpression Id. */
  int SEMICOLON = 129;
  /** RegularExpression Id. */
  int COMMA = 130;
  /** RegularExpression Id. */
  int DOT = 131;
  /** RegularExpression Id. */
  int AT = 132;
  /** RegularExpression Id. */
  int POUND = 133;
  /** RegularExpression Id. */
  int QUOTE = 134;
  /** RegularExpression Id. */
  int QUOTATION = 135;
  /** RegularExpression Id. */
  int ASSIGN = 136;
  /** RegularExpression Id. */
  int LT = 137;
  /** RegularExpression Id. */
  int BANG = 138;
  /** RegularExpression Id. */
  int TILDE = 139;
  /** RegularExpression Id. */
  int HOOK = 140;
  /** RegularExpression Id. */
  int COLON = 141;
  /** RegularExpression Id. */
  int EQ = 142;
  /** RegularExpression Id. */
  int LE = 143;
  /** RegularExpression Id. */
  int GE = 144;
  /** RegularExpression Id. */
  int NE = 145;
  /** RegularExpression Id. */
  int SC_OR = 146;
  /** RegularExpression Id. */
  int SC_AND = 147;
  /** RegularExpression Id. */
  int INCR = 148;
  /** RegularExpression Id. */
  int DECR = 149;
  /** RegularExpression Id. */
  int PLUS = 150;
  /** RegularExpression Id. */
  int MINUS = 151;
  /** RegularExpression Id. */
  int STAR = 152;
  /** RegularExpression Id. */
  int SLASH = 153;
  /** RegularExpression Id. */
  int BIT_AND = 154;
  /** RegularExpression Id. */
  int BIT_OR = 155;
  /** RegularExpression Id. */
  int XOR = 156;
  /** RegularExpression Id. */
  int REM = 157;
  /** RegularExpression Id. */
  int LSHIFT = 158;
  /** RegularExpression Id. */
  int PLUSASSIGN = 159;
  /** RegularExpression Id. */
  int MINUSASSIGN = 160;
  /** RegularExpression Id. */
  int STARASSIGN = 161;
  /** RegularExpression Id. */
  int SLASHASSIGN = 162;
  /** RegularExpression Id. */
  int ANDASSIGN = 163;
  /** RegularExpression Id. */
  int ORASSIGN = 164;
  /** RegularExpression Id. */
  int XORASSIGN = 165;
  /** RegularExpression Id. */
  int REMASSIGN = 166;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 167;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 168;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 169;
  /** RegularExpression Id. */
  int ELLIPSIS = 170;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"aspect\"",
    "\"after\"",
    "\"around\"",
    "\"before\"",
    "\"pointcut\"",
    "\"execution\"",
    "\"returning\"",
    "\"privileged\"",
    "\"call\"",
    "\"pertarget\"",
    "\"perthis\"",
    "\"percflow\"",
    "\"percflowbelow\"",
    "\"pertypewithin\"",
    "\"issingleton\"",
    "\"throwing\"",
    "\"proceed\"",
    "\"thisJoinPoint\"",
    "\"thisJoinPointStaticPart\"",
    "\"thisEnclosingJoinPointStaticPart\"",
    "\"declare\"",
    "\"parents\"",
    "\"warning\"",
    "\"error\"",
    "\"soft\"",
    "\"precedence\"",
    "\"@type\"",
    "\"@method\"",
    "\"@constructor\"",
    "\"@field\"",
    "\"initialization\"",
    "\"preinitialization\"",
    "\"staticinitialization\"",
    "\"get\"",
    "\"set\"",
    "\"handler\"",
    "\"adviceexecution\"",
    "\"within\"",
    "\"withincode\"",
    "\"cflow\"",
    "\"cflowbelow\"",
    "\"target\"",
    "\"args\"",
    "\"@this\"",
    "\"@target\"",
    "\"@args\"",
    "\"@within\"",
    "\"@annotation\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"#\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
  };

}
