/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package org.netbeans.aspectj.jccparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int ABSTRACT = 13;
  /** RegularExpression Id. */
  int ASSERT = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int BYTE = 17;
  /** RegularExpression Id. */
  int CASE = 18;
  /** RegularExpression Id. */
  int CATCH = 19;
  /** RegularExpression Id. */
  int CHAR = 20;
  /** RegularExpression Id. */
  int CLASS = 21;
  /** RegularExpression Id. */
  int CONST = 22;
  /** RegularExpression Id. */
  int CONTINUE = 23;
  /** RegularExpression Id. */
  int _DEFAULT = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int DOUBLE = 26;
  /** RegularExpression Id. */
  int ELSE = 27;
  /** RegularExpression Id. */
  int ENUM = 28;
  /** RegularExpression Id. */
  int EXTENDS = 29;
  /** RegularExpression Id. */
  int FALSE = 30;
  /** RegularExpression Id. */
  int FINAL = 31;
  /** RegularExpression Id. */
  int FINALLY = 32;
  /** RegularExpression Id. */
  int FLOAT = 33;
  /** RegularExpression Id. */
  int FOR = 34;
  /** RegularExpression Id. */
  int GOTO = 35;
  /** RegularExpression Id. */
  int IF = 36;
  /** RegularExpression Id. */
  int IMPLEMENTS = 37;
  /** RegularExpression Id. */
  int IMPORT = 38;
  /** RegularExpression Id. */
  int INSTANCEOF = 39;
  /** RegularExpression Id. */
  int INT = 40;
  /** RegularExpression Id. */
  int INTERFACE = 41;
  /** RegularExpression Id. */
  int LONG = 42;
  /** RegularExpression Id. */
  int NATIVE = 43;
  /** RegularExpression Id. */
  int NEW = 44;
  /** RegularExpression Id. */
  int NULL = 45;
  /** RegularExpression Id. */
  int PACKAGE = 46;
  /** RegularExpression Id. */
  int PRIVATE = 47;
  /** RegularExpression Id. */
  int PROTECTED = 48;
  /** RegularExpression Id. */
  int PUBLIC = 49;
  /** RegularExpression Id. */
  int RETURN = 50;
  /** RegularExpression Id. */
  int SHORT = 51;
  /** RegularExpression Id. */
  int STATIC = 52;
  /** RegularExpression Id. */
  int STRICTFP = 53;
  /** RegularExpression Id. */
  int SUPER = 54;
  /** RegularExpression Id. */
  int SWITCH = 55;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 56;
  /** RegularExpression Id. */
  int THIS = 57;
  /** RegularExpression Id. */
  int THROW = 58;
  /** RegularExpression Id. */
  int THROWS = 59;
  /** RegularExpression Id. */
  int TRANSIENT = 60;
  /** RegularExpression Id. */
  int TRUE = 61;
  /** RegularExpression Id. */
  int TRY = 62;
  /** RegularExpression Id. */
  int VOID = 63;
  /** RegularExpression Id. */
  int VOLATILE = 64;
  /** RegularExpression Id. */
  int WHILE = 65;
  /** RegularExpression Id. */
  int ASPECT = 66;
  /** RegularExpression Id. */
  int AFTER = 67;
  /** RegularExpression Id. */
  int AROUND = 68;
  /** RegularExpression Id. */
  int BEFORE = 69;
  /** RegularExpression Id. */
  int POINTCUT = 70;
  /** RegularExpression Id. */
  int EXECUTION = 71;
  /** RegularExpression Id. */
  int RETURNING = 72;
  /** RegularExpression Id. */
  int PRIVILEGED = 73;
  /** RegularExpression Id. */
  int CALL = 74;
  /** RegularExpression Id. */
  int PERTARGET = 75;
  /** RegularExpression Id. */
  int PERTHIS = 76;
  /** RegularExpression Id. */
  int PERCFLOW = 77;
  /** RegularExpression Id. */
  int PERCFLOWBELOW = 78;
  /** RegularExpression Id. */
  int PERTYPEWITHIN = 79;
  /** RegularExpression Id. */
  int ISSINGLETON = 80;
  /** RegularExpression Id. */
  int THROWING = 81;
  /** RegularExpression Id. */
  int PROCEED = 82;
  /** RegularExpression Id. */
  int THISJOINPOINT = 83;
  /** RegularExpression Id. */
  int THISJOINPOINTSTATICPART = 84;
  /** RegularExpression Id. */
  int THISENCLOSINGJOINPOINTSTATICPART = 85;
  /** RegularExpression Id. */
  int DECLARE = 86;
  /** RegularExpression Id. */
  int PARENTS = 87;
  /** RegularExpression Id. */
  int WARNING = 88;
  /** RegularExpression Id. */
  int ERROR = 89;
  /** RegularExpression Id. */
  int SOFT = 90;
  /** RegularExpression Id. */
  int PRECEDENCE = 91;
  /** RegularExpression Id. */
  int _TYPE = 92;
  /** RegularExpression Id. */
  int _METHOD = 93;
  /** RegularExpression Id. */
  int _CONSTRUCTOR = 94;
  /** RegularExpression Id. */
  int _FIELD = 95;
  /** RegularExpression Id. */
  int INITIALIZATION = 96;
  /** RegularExpression Id. */
  int PREINITIALIZATION = 97;
  /** RegularExpression Id. */
  int STATICINITIALIZATION = 98;
  /** RegularExpression Id. */
  int GET = 99;
  /** RegularExpression Id. */
  int SET = 100;
  /** RegularExpression Id. */
  int HANDLER = 101;
  /** RegularExpression Id. */
  int ADVICEEXECUTION = 102;
  /** RegularExpression Id. */
  int ADVICE = 103;
  /** RegularExpression Id. */
  int WITHIN = 104;
  /** RegularExpression Id. */
  int WITHINCODE = 105;
  /** RegularExpression Id. */
  int CFLOW = 106;
  /** RegularExpression Id. */
  int CFLOWBELOW = 107;
  /** RegularExpression Id. */
  int TARGET = 108;
  /** RegularExpression Id. */
  int ARGS = 109;
  /** RegularExpression Id. */
  int _THIS = 110;
  /** RegularExpression Id. */
  int _TARGET = 111;
  /** RegularExpression Id. */
  int _ARGS = 112;
  /** RegularExpression Id. */
  int _WITHIN = 113;
  /** RegularExpression Id. */
  int _ANNOTATION = 114;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 115;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 116;
  /** RegularExpression Id. */
  int HEX_LITERAL = 117;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 118;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 119;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 120;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 121;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 122;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 123;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 124;
  /** RegularExpression Id. */
  int STRING_LITERAL = 125;
  /** RegularExpression Id. */
  int IDENTIFIER = 126;
  /** RegularExpression Id. */
  int LETTER = 127;
  /** RegularExpression Id. */
  int PART_LETTER = 128;
  /** RegularExpression Id. */
  int LPAREN = 129;
  /** RegularExpression Id. */
  int RPAREN = 130;
  /** RegularExpression Id. */
  int LBRACE = 131;
  /** RegularExpression Id. */
  int RBRACE = 132;
  /** RegularExpression Id. */
  int LBRACKET = 133;
  /** RegularExpression Id. */
  int RBRACKET = 134;
  /** RegularExpression Id. */
  int SEMICOLON = 135;
  /** RegularExpression Id. */
  int COMMA = 136;
  /** RegularExpression Id. */
  int DOT = 137;
  /** RegularExpression Id. */
  int AT = 138;
  /** RegularExpression Id. */
  int ASSIGN = 139;
  /** RegularExpression Id. */
  int LT = 140;
  /** RegularExpression Id. */
  int BANG = 141;
  /** RegularExpression Id. */
  int TILDE = 142;
  /** RegularExpression Id. */
  int HOOK = 143;
  /** RegularExpression Id. */
  int COLON = 144;
  /** RegularExpression Id. */
  int EQ = 145;
  /** RegularExpression Id. */
  int LE = 146;
  /** RegularExpression Id. */
  int GE = 147;
  /** RegularExpression Id. */
  int NE = 148;
  /** RegularExpression Id. */
  int SC_OR = 149;
  /** RegularExpression Id. */
  int SC_AND = 150;
  /** RegularExpression Id. */
  int INCR = 151;
  /** RegularExpression Id. */
  int DECR = 152;
  /** RegularExpression Id. */
  int PLUS = 153;
  /** RegularExpression Id. */
  int MINUS = 154;
  /** RegularExpression Id. */
  int STAR = 155;
  /** RegularExpression Id. */
  int SLASH = 156;
  /** RegularExpression Id. */
  int BIT_AND = 157;
  /** RegularExpression Id. */
  int BIT_OR = 158;
  /** RegularExpression Id. */
  int XOR = 159;
  /** RegularExpression Id. */
  int REM = 160;
  /** RegularExpression Id. */
  int LSHIFT = 161;
  /** RegularExpression Id. */
  int PLUSASSIGN = 162;
  /** RegularExpression Id. */
  int MINUSASSIGN = 163;
  /** RegularExpression Id. */
  int STARASSIGN = 164;
  /** RegularExpression Id. */
  int SLASHASSIGN = 165;
  /** RegularExpression Id. */
  int ANDASSIGN = 166;
  /** RegularExpression Id. */
  int ORASSIGN = 167;
  /** RegularExpression Id. */
  int XORASSIGN = 168;
  /** RegularExpression Id. */
  int REMASSIGN = 169;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 170;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 171;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 172;
  /** RegularExpression Id. */
  int ELLIPSIS = 173;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 174;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 175;
  /** RegularExpression Id. */
  int GT = 176;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 178;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"():\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"aspect\"",
    "\"after\"",
    "\"around\"",
    "\"before\"",
    "\"pointcut\"",
    "\"execution\"",
    "\"returning\"",
    "\"privileged\"",
    "\"call\"",
    "\"pertarget\"",
    "\"perthis\"",
    "\"percflow\"",
    "\"percflowbelow\"",
    "\"pertypewithin\"",
    "\"issingleton\"",
    "\"throwing\"",
    "\"proceed\"",
    "\"thisJoinPoint\"",
    "\"thisJoinPointStaticPart\"",
    "\"thisEnclosingJoinPointStaticPart\"",
    "\"declare\"",
    "\"parents\"",
    "\"warning\"",
    "\"error\"",
    "\"soft\"",
    "\"precedence\"",
    "\"@type\"",
    "\"@method\"",
    "\"@constructor\"",
    "\"@field\"",
    "\"initialization\"",
    "\"preinitialization\"",
    "\"staticinitialization\"",
    "\"get\"",
    "\"set\"",
    "\"handler\"",
    "\"adviceexecution\"",
    "\"advice\"",
    "\"within\"",
    "\"withincode\"",
    "\"cflow\"",
    "\"cflowbelow\"",
    "\"target\"",
    "\"args\"",
    "\"@this\"",
    "\"@target\"",
    "\"@args\"",
    "\"@within\"",
    "\"@annotation\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
    "\"*.\"",
    "\"..\"",
    "\"*..*\"",
    "\".*\"",
  };

}
